### ISSUE TITLE
collaborate with socket.io

### ISSUE THREAD

**Issue by leonidkuznetsov18** [convergencelabs/html-text-collab-ext#1]
Very good application, but maybe you thought about creating realtime editing in one textarea with multiple connection(analogue Google Docs) with socket.io and lib dif_patch_match?

**Comment by alalonde** [comment]
Hi there, thanks for the feedback!  This component was designed to be agnostic of any particular data sync library.  If you're interested, I just added a link to this repo's README (beneath the demo gif) showing a live example that uses [Convergence](https://convergence.io).

**Comment by curran** [comment]
Here's an example that uses WebSockets and ShareDB:
https://github.com/datavis-tech/json0-presence-demo
